backend:
  name: github
  repo: flockcover/flock

publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: "src/pages/index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Template key", name: "templateKey", widget: "string"}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Header", name: "header", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - name: "button"
                label: "Button"
                widget: "object"
                fields:
                  - {label: "Text", name: "text", widget: "string"}
                  - {label: "To", name: "to", widget: "string"}
          - label: 'Video'
            name: video
            widget: object
            fields:
              - {name: isShowing, label: 'Show video?', widget: boolean}
              - {label: 'Text', name: 'text', widget: 'string'}
              - {label: 'YouTube ID', name: 'id', widget: 'string'}
              - {label: 'Cover image', name: 'coverImage', widget: 'image'}
          - label: 'How Flock works'
            name: 'howFlockWorks'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - label: 'List of how'
                name: 'listOfHow'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Text', name: 'text', widget: 'markdown'}
                  - {label: 'Image', name: 'image', widget: 'image'}
          - label: 'Stop worrying'
            name: 'stopWorrying'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - label: 'Reasons'
                name: 'reasons'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Text', name: 'text', widget: 'markdown'}
                  - {label: 'Icon', name: 'icon', widget: 'image'}
          - label: 'What kind of pilot?'
            name: 'kindOfPilot'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'string'}
              - label: 'Products'
                name: 'products'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Text', name: 'text', widget: 'markdown'}
                  - {label: 'Icon', name: 'icon', widget: 'image'}
                  - {label: 'Link', name: 'link', widget: 'string'}
          - label: 'Risk'
            name: 'risk'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'markdown'}
              - label: 'List'
                name: 'list'
                widget: 'list'
                fields:
                  - {label: 'Title', name: 'title', widget: 'string'}
                  - {label: 'Text', name: 'text', widget: 'markdown'}
                  - {label: 'Icon', name: 'icon', widget: 'image'}
          - label: 'Calculator'
            name: 'calculator'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'string'}
              - {label: 'Disclaimer', name: 'disclaimer', widget: 'string'}
          - label: 'Second testimonials'
            name: 'secondTestimonial'
            widget: 'list'
            fields:
              - {label: 'Author', name: 'author', widget: 'string'}
              - {label: 'Quote', name: 'quote', widget: 'markdown'}
              - {label: 'Image', name: 'image', widget: 'image'}
          - label: 'Featured'
            name: 'featured'
            widget: 'object'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Image', name: 'image', widget: 'image'}
          - name: "siteMetadataOverride"
            required: false
            label: "Site metadata override"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Keywords", name: "keywords", widget: "list"}
      - name: settings
        label: Settings
        file: "src/pages/settings.md"
        fields:
          - label: "Site metadata"
            name: "siteMetadata"
            required: false
            widget: "object"
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Description', name: 'description', widget: 'string'}
              - {label: 'Keywords', name: 'keywords', widget: 'array'}
      - name: pricing
        label: Pricing
        file: "src/pages/pricing.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - { name: templateKey, label: Template key, widget: 'hidden', default: pricing }
          - name: hero
            label: Hero
            widget: object
            fields:
              - {name: 'header', label: 'Header', widget: 'string'}
              - {name: 'backgroundImage', label: 'Background image', widget: 'image'}
          - name: 'riskCalculations'
            label: 'Risk calculations'
            widget: object
            fields:
              - {name: 'image', label: 'Image', widget: 'image'}
              - {name: 'description', label: 'Description', widget: 'string'}
              - name: 'calculations'
                label: 'Calculations'
                widget: 'list'
                fields:
                  - {name: 'title', label: 'Title', widget: 'string'}
                  - {name: 'text', label: 'Text', widget: 'string'}
                  - {name: 'icon', label: 'Icon', required: false, widget: image}
          - name: 'siteMetadataOverride'
            label: 'Site metadata override'
            required: false
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Keywords", name: "keywords", widget: "list"}
      - name: about
        label: About
        file: "src/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - { name: templateKey, label: Template key, widget: 'hidden', default: product }
          - name: hero
            label: Hero
            widget: object
            fields:
              - {name: 'backgroundImage', label: Background image, widget: 'image'}
              - {name: 'header', label: 'Header', widget: 'string'}
          - name: flockStory
            label: Flock story
            widget: object
            fields:
              - {name: 'header', label: 'Header', widget: 'string'}
              - {name: 'image', label: 'Image', widget: 'image'}
              - {name: 'imageHeader', label: 'Image header', widget: 'string'}
              - {name: 'bigText', label: 'Big text', widget: 'markdown'}
              - {name: 'smallText', label: 'Small text', widget: 'markdown'}
          - name: coreValues
            label: Core values
            widget: object
            fields:
              - {name: isShowing, label: 'Show Core Values?', widget: boolean}
              - {name: 'title', label: 'Title', widget: 'string'}
              - {name: 'description', label: 'Description', widget: 'markdown'}
              - label: 'List'
                name: 'list'
                widget: 'list'
                fields:
                  - {label: 'Text', name: 'text', widget: 'markdown'}
                  - {label: 'Title', name: 'title', widget: 'markdown'}
          - name: meetTheTeam
            label: Meet the team
            widget: object
            fields:
              - {name: 'title', label: 'Title', widget: 'string'}
              - {name: 'description', label: 'Description', widget: 'markdown'}
              - label: 'Team'
                name: 'team'
                widget: 'list'
                fields:
                  - {label: 'Member', name: 'member', widget: 'string'}
                  - {label: 'Role', name: 'role', widget: 'markdown'}
                  - {label: 'Image', name: 'image', widget: 'image'}
          - name: "siteMetadataOverride"
            label: "Site metadata override"
            required: false
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "string"}
              - {label: "Keywords", name: "keywords", widget: "list"}

  - name: products
    label: Products
    folder: src/pages/insurance
    create: true
    fields:
      - { name: title, label: Title }
      - { name: templateKey, label: Template key, widget: 'hidden', default: product }
      - name: hero
        label: Hero
        widget: object
        fields:
          - name: 'button'
            label: 'Button'
            widget: 'object'
            fields:
              - {name: 'text', label: 'Text', widget: 'string'}
              - {name: 'to', label: 'To', widget: 'string'}
          - {name: 'description', label: 'Description', widget: 'markdown'}
          - {name: 'header', label: 'Header', widget: 'string'}
          - {name: 'backgroundImage', label: 'Background image', widget: 'image'}
      - label: 'Why'
        name: 'why'
        widget: 'object'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Description', name: 'description', widget: 'markdown'}
          - label: 'List'
            name: 'list'
            widget: 'list'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Text', name: 'text', widget: 'markdown'}
      - label: 'Flight school'
        name: 'flightSchool'
        widget: 'object'
        fields:
          - {label: 'Show flight school list?', name: 'show', widget: 'boolean'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - name: 'list'
            label: 'Flight schools'
            widget: list
            fields:
              - {name: image, label: Image, widget: image}
              - {name: to, label: Link, widget: string}
      - label: 'Cover note'
        name: coverNote
        widget: object
        fields:
          - {name: isShowing, label: 'Show cover note?', widget: boolean}
          - {name: image, label: Image, widget: image}
          - {name: title, label: Title, widget: string}
          - {name: bodyText, label: Body text, widget: string}
          - {name: smallText, label: Small text, widget: string}
          - name: link
            label: Link
            widget: object
            fields:
              - {name: to, label: To, widget: string}
              - {name: text, label: Text, widget: string}
      - label: 'Do I need insurance'
        name: 'doINeedInsurance'
        widget: object
        fields:
          - {title: Title, name: title, widget: markdown}
          - {title: BigText, name: bigText, widget: markdown}
          - {title: SmallText, name: smallText, widget: markdown}
      - label: 'How'
        name: 'how'
        widget: 'object'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Description', name: 'description', widget: 'markdown'}
          - label: 'List'
            name: 'list'
            widget: 'list'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Text', name: 'text', widget: 'markdown'}
              - {label: 'Image', name: 'image', widget: 'image'}
      - label: 'Risk'
        name: 'risk'
        widget: 'object'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Description', name: 'description', widget: 'markdown'}
          - label: 'List'
            name: 'list'
            widget: 'list'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Text', name: 'text', widget: 'text'}
              - {label: 'Icon', name: 'icon', widget: 'image'}
      - label: 'Testimonials'
        name: 'testimonial'
        widget: 'list'
        fields:
          - {label: 'Author', name: 'author', widget: 'string'}
          - {label: 'Quote', name: 'quote', widget: 'markdown'}
          - {label: 'Image', name: 'image', widget: 'image'}
      - label: 'Other products'
        name: 'otherProducts'
        widget: 'object'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Description', name: 'description', widget: 'markdown'}
          - label: 'Products'
            name: 'products'
            widget: 'list'
            fields:
              - {label: 'Title', name: 'title', widget: 'string'}
              - {label: 'Text', name: 'text', widget: 'markdown'}
              - {label: 'Icon', name: 'icon', widget: 'image'}
              - {label: 'Link', name: 'link', widget: 'string'}
      - name: "siteMetadataOverride"
        label: "Site metadata override"
        required: false
        widget: "object"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Keywords", name: "keywords", widget: "list"}
